CREATE TABLE records (
	id bigint generated by default as identity primary key,
  title text,
  calories INT not null default 0,
	created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE POLICY "Enable read posts for all users"
ON "public"."records"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable all methods for my email only"
on "public"."records"
as permissive
for all
to authenticated
using (((auth.jwt() ->> 'email'::text) = 'julius.zlioba@gmail.com'::text));

ALTER TABLE "public"."records" ENABLE ROW LEVEL SECURITY;

CREATE TABLE totals (
	id bigint generated by default as identity primary key,
  calories INT not null default 0,
	date text not null unique
);

CREATE POLICY "Enable read posts for all users"
ON "public"."totals"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable all methods for my email only"
on "public"."totals"
as permissive
for all
to authenticated
using (((auth.jwt() ->> 'email'::text) = 'julius.zlioba@gmail.com'::text));

ALTER TABLE "public"."totals" ENABLE ROW LEVEL SECURITY;